export const RESET_STAINS = "RESET_STAINS";
export const GET_STAINS_INIT = "GET_STAINS_INIT";
export const GET_STAINS_SUCCESS = "GET_STAINS_SUCCESS";
export const GET_STAINS_FAILURE = "GET_STAINS_FAILURE";

export const RESET_PUT_STAIN = "RESET_PUT_STAIN";
export const PUT_STAIN_INIT = "PUT_STAIN_INIT";
export const PUT_STAIN_SUCCESS = "PUT_STAIN_SUCCESS";
export const PUT_STAIN_FAILURE = "PUT_STAIN_FAILURE";
