export const RESET_GROUPS = "RESET_GROUPS";
export const GET_GROUPS_INIT = "GET_GROUPS_INIT";
export const GET_GROUPS_SUCCESS = "GET_GROUPS_SUCCESS";
export const GET_GROUPS_FAILURE = "GET_GROUPS_FAILURE";
