export const POST_GROUP_INIT = "POST_GROUP_INIT";
export const POST_GROUP_SUCCESS = "POST_GROUP_SUCCESS";
export const POST_GROUP_FAILURE = "POST_GROUP_FAILURE";
export const RESET_GROUP = "RESET_GROUP";
