export const GET_LOGIN_INIT = "GET_LOGIN_INIT";
export const GET_LOGIN_SUCCESS = "GET_LOGIN_SUCCESS";
export const GET_LOGIN_FAILURE = "GET_LOGIN_FAILURE";
export const RESET_LOGIN = "RESET_LOGIN";

export const GET_LABORATORY_INIT = "GET_LABORATORY_INIT";
export const GET_LABORATORY_SUCCESS = "GET_LABORATORY_SUCCESS";
export const GET_LABORATORY_FAILURE = "GET_LABORATORY_FAILURE";
export const RESET_LABORATORY = "RESET_LABORATORY";

export const POST_REGISTER_INIT = "POST_REGISTER_INIT";
export const POST_REGISTER_SUCCESS = "POST_REGISTER_SUCCESS";
export const POST_REGISTER_FAILURE = "POST_REGISTER_FAILURE";
export const RESET_REGISTER = "RESET_REGISTER";
