export const RESET_PUT_GROUP = "RESET_PUT_GROUP";
export const PUT_GROUP_INIT = "PUT_GROUP_INIT";
export const PUT_GROUP_SUCCESS = "PUT_GROUP_SUCCESS";
export const PUT_GROUP_FAILURE = "PUT_GROUP_FAILURE";

export const RESET_GROUP = "RESET_GROUP";
export const GET_GROUP_INIT = "GET_GROUP_INIT";
export const GET_GROUP_SUCCESS = "GET_GROUP_SUCCESS";
export const GET_GROUP_FAILURE = "GET_GROUP_FAILURE";
