export const POST_STAIN_INIT = "POST_STAIN_INIT";
export const POST_STAIN_SUCCESS = "POST_STAIN_SUCCESS";
export const POST_STAIN_FAILURE = "POST_STAIN_FAILURE";
export const RESET_STAIN = "RESET_STAIN";
